# Go Project Configuration
# Comprehensive configuration for Go projects with modern development practices
# Includes Go-specific validation rules and strict quality standards

validation:
  agents:
    essential-files:
      enabled: true
      require_readme: true
      require_contributing: true
      require_docs_directory: true
      docs_requirements:
        require_usage_guide: true
        require_examples: true
        min_doc_files: 3
      custom_files:
        - pattern: "LICENSE*"
          required: true
          description: "License file required"
        - pattern: "go.mod"
          required: true
          description: "Go module file"
        - pattern: "Taskfile.yml"
          required: true
          description: "Task automation file"
          
    git-configuration:
      enabled: true
      require_gitignore: true
      require_gitattributes: true
      require_editorconfig: true
      validation_rules:
        gitignore_validation: true
        gitattributes_validation: true
      gitignore_validation:
        check_language_specific: true
        detect_project_type: true
        required_patterns:
          go: 
            - "*.exe"
            - "*.test"
            - "*.out"
            - "vendor/"
            - "bin/"
            
    development-standards:
      enabled: true
      check_commit_history: true
      commit_history_depth: 15
      require_conventional_commits: true
      validation_threshold: 0.8
      conventional_commits:
        allowed_types:
          - "feat"
          - "fix"
          - "docs"
          - "style"
          - "refactor"
          - "test"
          - "chore"
          - "perf"
          - "ci"
          - "build"

  output:
    format: "table"
    verbose: true

  scoring:
    pass_threshold: 0.85
    warning_threshold: 0.7
