version: 2

project_name: codebase-interface

before:
  hooks:
    - sh -c "cd cli && go mod tidy"

builds:
  - id: codebase-interface
    main: .
    binary: codebase-interface
    dir: cli
    env:
      - CGO_ENABLED=0
    flags: [ -trimpath ]
    ldflags: [ -s -w ]
    goos: [ linux, darwin, windows ]
    goarch: [ amd64, arm64 ]

archives:
  - id: default
    builds: [ codebase-interface ]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

brews:
  - name: codebase-interface
    repository:
      owner: codebase-interface         # your GitHub user/org
      name: homebrew-tap
    commit_author:
      name: GoReleaser
      email: noreply@goreleaser.com
    directory: Formula
    description: "A zero-dependency JSON-driven CLI"
    homepage: "https://github.com/codebase-interface/cli"
    install: |
      bin.install "codebase-interface"
    test: |
      system "#{bin}/codebase-interface", "--version"
checksum:
  name_template: "SHA256SUMS.txt"
  algorithm: sha256

release:
  draft: false
  github:
    owner: codebase-interface        
    name: codebase-interface          

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'