version: '3'

tasks:
  build:
    desc: Build the CLI binary
    cmds:
      - go build -o bin/codebase-cli ./cmd/codebase-cli

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test:watch:
    desc: Run tests in watch mode
    deps: [install-gotestsum]
    cmds:
      - gotestsum --watch

  lint:
    desc: Run linting
    deps: [install-golangci-lint]
    cmds:
      - golangci-lint run

  tidy:
    desc: Tidy Go modules
    cmds:
      - go mod tidy

  install:
    desc: Install CLI locally
    cmds:
      - go install ./cmd/codebase-cli

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/

  setup:
    desc: Set up development environment
    deps: [install-gotestsum, install-golangci-lint, docs:install]
    cmds:
      - go mod download

  install-gotestsum:
    desc: Install gotestsum for test watching
    cmds:
      - go install gotest.tools/gotestsum@latest
    status:
      - which gotestsum

  install-golangci-lint:
    desc: Install golangci-lint for linting
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    status:
      - which golangci-lint

  validate-self:
    desc: Run the CLI on itself for validation
    deps: [build]
    cmds:
      - ./bin/codebase-cli validate

  dev:
    desc: Development workflow - build and test
    deps: [build, test]

  docs:serve:
    desc: Serve documentation using MkDocs
    cmds:
      - |
        echo "📚 Serving documentation with MkDocs at http://localhost:8000"
        echo "Press Ctrl+C to stop the server"
        mkdocs serve

  docs:build:
    desc: Build static documentation site
    cmds:
      - mkdocs build
      - echo "📦 Documentation built in site/ directory"

  docs:open:
    desc: Serve documentation and open in browser
    cmds:
      - |
        echo "🚀 Starting MkDocs server and opening browser..."
        (sleep 3 && (
          if command -v xdg-open > /dev/null 2>&1; then
            xdg-open http://localhost:8000
          elif command -v open > /dev/null 2>&1; then
            open http://localhost:8000
          else
            echo "Please open http://localhost:8000 in your browser"
          fi
        )) &
        mkdocs serve

  docs:install:
    desc: Install MkDocs and required plugins
    cmds:
      - pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin
      - echo "📚 MkDocs installed successfully"

  docs:check:
    desc: Check documentation for common issues (links, formatting)
    cmds:
      - |
        echo "🔍 Checking documentation..."
        find docs/ -name "*.md" -exec echo "Checking {}" \; -exec grep -l "TODO\|FIXME\|XXX" {} \; || true
        echo "✅ Documentation check complete"